#!/usr/bin/env python3
from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parent
BOOTSTRAP = ROOT / '.agentwork' / 'bootstrap'
DATA = BOOTSTRAP / 'data'
SHARED_ROOT = ROOT / '.shared'
TOOLS_ROOT = ROOT / '.agentwork' / 'tools'
REGISTRY = TOOLS_ROOT / 'registry.json'

BLOCK_TARGETS = [
    (Path('.shared/project/index.md'), DATA / 'project-index.block.md', '# Project 索引\n\n## 本项目自定义内容\n'),
    (Path('.shared/session/README.md'), DATA / 'session-readme.block.md', '# Session 目录说明\n\n## 本项目补充说明\n'),
]
GITIGNORE_BLOCK_START = '# >>> AGENTWORK bootstrap: tmp artifacts >>>'
GITIGNORE_BLOCK_END = '# <<< AGENTWORK bootstrap: tmp artifacts <<<'
GITIGNORE_BLOCK = '\n'.join(
    [
        GITIGNORE_BLOCK_START,
        '.tmp/',
        GITIGNORE_BLOCK_END,
    ]
)
TMP_GITIGNORE_PATTERNS = {
    '.tmp',
    '.tmp/',
    '.tmp/*',
    '/.tmp',
    '/.tmp/',
    '/.tmp/*',
}
AGENTWORK_BOOTSTRAP_MARKER = '<!-- AUTO-GENERATED by agentwork bootstrap -->'
CODEX_AGENT_MARKER = '# AUTO-GENERATED by agentwork bootstrap'
CODEX_CONFIG_BLOCK = BOOTSTRAP / 'codex' / 'config.block.toml'
CODEX_CONFIG_BLOCK_START = '# >>> AGENTWORK bootstrap: Codex agents >>>'
CODEX_CONFIG_BLOCK_END = '# <<< AGENTWORK bootstrap: Codex agents <<<'
RETIRED_BOOTSTRAP_PATHS = (
    Path('.agent/rules/bootstrap.md'),
    Path('.agent/workflows/brain.md'),
    Path('.agent/workflows/commit.md'),
    Path('.agent/workflows/exec.md'),
    Path('.agent/workflows/plan.md'),
    Path('.agent/workflows/review.md'),
    Path('.agent/workflows/session.md'),
    Path('.github/copilot-instructions.md'),
)
RETIRED_TOOL_SIGNATURES = {
    Path('.agent/skills/browser/SKILL.md'): ('# browser', '.shared/skills/browser/SKILL.md'),
    Path('.agent/workflows/android.md'): ('# /android', '.shared/commands/android.md'),
    Path('.agent/workflows/arch.md'): ('# /arch', '.shared/commands/arch.md'),
    Path('.agent/workflows/figma.md'): ('# /figma', '.shared/commands/figma.md'),
    Path('.agent/workflows/godot.md'): ('# /godot', '.shared/commands/godot.md'),
    Path('.github/prompts/android.instructions.md'): ('# Android Tool Instructions', '.shared/commands/android.md'),
    Path('.github/prompts/arch.instructions.md'): ('# Arch Tool Instructions', '.shared/commands/arch.md'),
    Path('.github/prompts/browser.instructions.md'): ('# Browser Tool Instructions', '.shared/skills/browser/SKILL.md'),
    Path('.github/prompts/figma.instructions.md'): ('# Figma Tool Instructions', '.shared/commands/figma.md'),
    Path('.github/prompts/godot.instructions.md'): ('# Godot Tool Instructions', '.shared/commands/godot.md'),
}
RETIRED_ADAPTER_PATHS = RETIRED_BOOTSTRAP_PATHS + tuple(RETIRED_TOOL_SIGNATURES)
RECEIPT_SCHEMA_VERSION = 1
RECEIPT_REL = Path('.agentwork/bootstrap-install-state.json')
SHA256_PATTERN = re.compile(r'^[0-9a-f]{64}$')


@dataclass(frozen=True)
class PreparedFile:
    path: Path
    content: bytes


@dataclass(frozen=True)
class PathSnapshot:
    path: Path
    kind: str
    backup: Path | None


@dataclass(frozen=True)
class BootstrapPlan:
    target: Path
    writes: tuple[tuple[Path, Path, str, str], ...]
    retired_removed: tuple[Path, ...]
    retired_preserved: tuple[Path, ...]
    managed_indexes: tuple[PreparedFile, ...]
    codex_config: PreparedFile
    gitignore: PreparedFile
    gitignore_status: str
    gitignore_changed: bool
    receipt: PreparedFile
    transaction_paths: tuple[Path, ...]


def is_python_cache_artifact(rel: Path) -> bool:
    return '__pycache__' in rel.parts or rel.suffix in {'.pyc', '.pyo'}


def copy_file(src: Path, dst: Path) -> None:
    if src.resolve() == dst.resolve():
        return
    if dst.exists() and dst.is_dir():
        raise SystemExit(f'target path is a directory, expected file: {dst}')
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def prune_empty_parents(path: Path, project_root: Path) -> None:
    current = path
    while current != project_root and current.exists():
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent


def is_agentwork_owned_retired_adapter(rel: Path, path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeError):
        return False
    if rel in RETIRED_BOOTSTRAP_PATHS:
        return AGENTWORK_BOOTSTRAP_MARKER in text
    signatures = RETIRED_TOOL_SIGNATURES.get(rel, ())
    return bool(signatures) and all(signature in text for signature in signatures)


def classify_retired_adapters(target: Path) -> tuple[tuple[Path, ...], tuple[Path, ...]]:
    removed = []
    preserved = []
    for rel in RETIRED_ADAPTER_PATHS:
        path = target / rel
        if not path.is_file() and not path.is_symlink():
            continue
        if not is_agentwork_owned_retired_adapter(rel, path):
            preserved.append(rel)
            continue
        removed.append(rel)
    return tuple(removed), tuple(preserved)


def remove_retired_adapters(target: Path, paths: tuple[Path, ...]) -> None:
    for rel in paths:
        path = target / rel
        path.unlink()
        prune_empty_parents(path.parent, target)


def refresh_generated_bootstrap() -> None:
    renderer = BOOTSTRAP / 'render_bootstrap.py'
    if renderer.exists():
        subprocess.run([sys.executable, str(renderer)], check=True)


def load_tool_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding='utf-8'))


def is_path_covered(path: Path, declared_paths: set[Path]) -> bool:
    return any(path == declared or declared in path.parents for declared in declared_paths)


def collect_optional_shared_relpaths() -> set[Path]:
    relpaths: set[Path] = set()
    registry = load_tool_registry()
    for tool in registry.get('tools', []):
        tool_dir = TOOLS_ROOT / tool['dir']
        tool_meta = json.loads((tool_dir / 'tool.json').read_text(encoding='utf-8'))
        entries = tool_meta.get('entries', [])
        declared_sources = {
            Path(entry['from'])
            for entry in entries
            if entry.get('from', '').startswith('shared/') and entry.get('to', '').startswith('.shared/')
        }
        shared_dir = tool_dir / 'shared'
        missing = []
        if shared_dir.exists():
            missing = [
                path.relative_to(tool_dir)
                for path in sorted(shared_dir.rglob('*'))
                if path.is_file()
                and not is_python_cache_artifact(path.relative_to(tool_dir))
                and not is_path_covered(path.relative_to(tool_dir), declared_sources)
            ]
        if missing:
            details = ', '.join(str(path) for path in missing)
            raise SystemExit(f'optional tool shared files missing from tool.json entries ({tool_dir.name}): {details}')

        for entry in entries:
            target = entry.get('to', '')
            if target.startswith('.shared/'):
                relpaths.add(Path(target.removeprefix('.shared/')))
    return relpaths


def collect_core_shared_writes(target: Path):
    writes = []
    optional_shared_relpaths = collect_optional_shared_relpaths()
    for src in sorted(x for x in SHARED_ROOT.rglob('*') if x.is_file()):
        rel = src.relative_to(SHARED_ROOT)
        if is_python_cache_artifact(rel):
            continue
        if rel.parts and rel.parts[0] in {'project', 'session'}:
            continue
        if is_path_covered(rel, optional_shared_relpaths):
            continue
        writes.append((src, target / '.shared' / rel, 'file', 'core shared file'))
    return writes


def collect_writes(target: Path):
    writes = []
    writes.extend(collect_core_shared_writes(target))
    root_bootstrap = ROOT / 'AGENTS.md' if target.resolve() == ROOT.resolve() else BOOTSTRAP / 'root' / 'AGENTS.md'
    writes.append((root_bootstrap, target / 'AGENTS.md', 'file', 'root bootstrap file'))
    writes.append((BOOTSTRAP / 'claude' / 'CLAUDE.md', target / '.claude' / 'CLAUDE.md', 'file', 'Claude bootstrap file'))
    for src in sorted((BOOTSTRAP / 'claude' / 'commands').glob('*.md')):
        writes.append((src, target / '.claude' / 'commands' / src.name, 'file', 'Claude wrapper'))
    writes.append((BOOTSTRAP / 'cursor' / 'rules' / 'agentwork-bootstrap.mdc', target / '.cursor' / 'rules' / 'agentwork-bootstrap.mdc', 'file', 'Cursor rule'))
    codex_skills = BOOTSTRAP / 'codex' / 'skills'
    for src in sorted(path for path in codex_skills.rglob('*') if path.is_file()):
        if is_python_cache_artifact(src.relative_to(codex_skills)):
            continue
        writes.append((src, target / '.codex' / 'skills' / src.relative_to(codex_skills), 'file', 'Codex skill wrapper'))
    for agent in load_codex_agents():
        src = BOOTSTRAP / 'codex' / 'agents' / agent['file']
        writes.append((src, target / '.codex' / 'agents' / src.name, 'file', 'Codex agent'))
    for src in sorted((BOOTSTRAP / 'opencode' / 'commands').glob('*.md')):
        writes.append((src, target / '.opencode' / 'commands' / src.name, 'file', 'OpenCode command wrapper'))
    opencode_gitignore = BOOTSTRAP / 'opencode' / '.gitignore'
    if opencode_gitignore.exists():
        writes.append((opencode_gitignore, target / '.opencode' / '.gitignore', 'file', 'OpenCode dir gitignore'))
    return writes


def managed_block_span(
    text: str,
    start_marker: str,
    end_marker: str,
    label: str,
) -> tuple[int, int] | None:
    start_count = text.count(start_marker)
    end_count = text.count(end_marker)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise SystemExit(f'{label} has a malformed or duplicate agentwork managed block')
    start_idx = text.find(start_marker)
    end_idx = text.find(end_marker)
    if start_idx >= end_idx:
        raise SystemExit(f'{label} has an invalid agentwork managed block')
    return start_idx, end_idx + len(end_marker)


def strip_managed_codex_config_block(text: str) -> tuple[str, bool]:
    span = managed_block_span(
        text,
        CODEX_CONFIG_BLOCK_START,
        CODEX_CONFIG_BLOCK_END,
        'Codex config',
    )
    if span is None:
        return text, False
    start_idx, end_idx = span
    return text[:start_idx] + text[end_idx:], True


def load_codex_agents() -> list[dict]:
    spec = json.loads((BOOTSTRAP / 'spec.json').read_text(encoding='utf-8'))
    return spec['codex_agents']


def reject_symlink_path(path: Path, target: Path, label: str) -> None:
    current = path
    while current != target:
        if current.is_symlink():
            raise SystemExit(f'cannot manage {label} through symlink: {current}')
        current = current.parent


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def receipt_path(target: Path) -> Path:
    return target / RECEIPT_REL


def load_receipt(target: Path) -> dict[str, str]:
    path = receipt_path(target)
    reject_symlink_path(path, target, 'bootstrap receipt')
    if not path.exists():
        return {}
    if not path.is_file():
        raise SystemExit(f'cannot read bootstrap receipt path: {path}')
    try:
        data = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SystemExit(f'invalid bootstrap receipt: {path}: {exc}') from exc
    if not isinstance(data, dict) or set(data) != {'schema_version', 'files'}:
        raise SystemExit(f'invalid bootstrap receipt structure: {path}')
    if data['schema_version'] != RECEIPT_SCHEMA_VERSION or not isinstance(data['files'], list):
        raise SystemExit(f'unsupported bootstrap receipt schema: {path}')

    result: dict[str, str] = {}
    for index, entry in enumerate(data['files']):
        if not isinstance(entry, dict) or set(entry) != {'path', 'type', 'sha256'}:
            raise SystemExit(f'invalid bootstrap receipt entry {index}: {path}')
        raw_rel = entry['path']
        digest = entry['sha256']
        if (
            not isinstance(raw_rel, str)
            or not raw_rel
            or '\\' in raw_rel
            or Path(raw_rel).is_absolute()
            or Path(raw_rel) == Path('.')
            or '..' in Path(raw_rel).parts
        ):
            raise SystemExit(f'invalid bootstrap receipt path at entry {index}: {path}')
        if entry['type'] != 'file' or not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
            raise SystemExit(f'invalid bootstrap receipt metadata at entry {index}: {path}')
        normalized = Path(raw_rel).as_posix()
        if normalized != raw_rel or normalized in result:
            raise SystemExit(f'duplicate or non-canonical bootstrap receipt path at entry {index}: {path}')
        reject_symlink_path(target / normalized, target, 'bootstrap receipt entry')
        result[normalized] = digest
    return result


def build_receipt(target: Path, writes) -> bytes:
    entries = []
    seen: set[str] = set()
    for src, dst, kind, _ in writes:
        if kind != 'file':
            raise SystemExit(f'unsupported bootstrap receipt entry type: {kind}')
        try:
            rel = dst.relative_to(target).as_posix()
        except ValueError as exc:
            raise SystemExit(f'bootstrap target escapes project root: {dst}') from exc
        if rel in seen:
            raise SystemExit(f'duplicate bootstrap write target: {rel}')
        seen.add(rel)
        entries.append({'path': rel, 'type': 'file', 'sha256': sha256_bytes(src.read_bytes())})
    data = {'schema_version': RECEIPT_SCHEMA_VERSION, 'files': sorted(entries, key=lambda entry: entry['path'])}
    return (json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + '\n').encode('utf-8')


def write_receipt(target: Path, content: bytes) -> None:
    path = receipt_path(target)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(prefix=f'.{path.name}.', dir=path.parent, delete=False) as handle:
            temp_name = handle.name
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        if temp_name is not None:
            try:
                Path(temp_name).unlink()
            except FileNotFoundError:
                pass


def symlink_in_path(path: Path, target: Path) -> Path | None:
    current = path
    while current != target:
        if current.is_symlink():
            return current
        current = current.parent
    return None


def has_matching_generated_marker(source: bytes, existing: bytes) -> bool:
    markers = (AGENTWORK_BOOTSTRAP_MARKER.encode('utf-8'), CODEX_AGENT_MARKER.encode('utf-8'))
    return any(marker in source and marker in existing for marker in markers)


def preflight_writes(target: Path, writes, previous: dict[str, str]) -> None:
    conflicts: list[tuple[str, str]] = []
    for src, dst, kind, _ in writes:
        if kind != 'file':
            conflicts.append((target_rel(target, dst), f'unsupported managed type: {kind}'))
            continue
        if src.resolve() == dst.resolve():
            continue
        rel = target_rel(target, dst)
        symlink = symlink_in_path(dst, target)
        if symlink is not None:
            conflicts.append((rel, f'path contains symlink: {target_rel(target, symlink)}'))
            continue
        if not dst.exists():
            continue
        if not dst.is_file():
            conflicts.append((rel, 'target is not a regular file'))
            continue
        try:
            source = src.read_bytes()
            existing = dst.read_bytes()
        except OSError as exc:
            conflicts.append((rel, f'cannot read source or target: {exc}'))
            continue
        if existing == source:
            continue
        prior_digest = previous.get(rel)
        if prior_digest is not None:
            if sha256_bytes(existing) == prior_digest:
                continue
            conflicts.append((rel, 'content changed since the last successful bootstrap install'))
            continue
        if has_matching_generated_marker(source, existing):
            continue
        conflicts.append((rel, 'existing content is not recognized as agentwork-managed'))
    if conflicts:
        details = '\n'.join(f'- {rel}: {reason}' for rel, reason in sorted(conflicts))
        raise SystemExit(f'bootstrap ownership conflicts:\n{details}')


def prepare_codex_config(target: Path) -> tuple[Path, bytes]:
    config = target / '.codex' / 'config.toml'
    reject_symlink_path(config, target, 'Codex config')
    if config.exists() and not config.is_file():
        raise SystemExit(f'cannot manage Codex config path: {config}')
    try:
        original = config.read_bytes().decode('utf-8') if config.exists() else ''
    except UnicodeDecodeError as exc:
        raise SystemExit(f'cannot update non-UTF-8 Codex config: {config}') from exc
    unmanaged, had_block = strip_managed_codex_config_block(original)
    try:
        parsed = tomllib.loads(unmanaged) if unmanaged.strip() else {}
    except tomllib.TOMLDecodeError as exc:
        raise SystemExit(f'cannot update invalid Codex config: {config}: {exc}') from exc
    agents = parsed.get('agents', {})
    if not isinstance(agents, dict):
        raise SystemExit(f'Codex config agents value must be a table: {config}')
    conflicts = sorted({agent['name'] for agent in load_codex_agents()} & set(agents))
    if conflicts:
        names = ', '.join(conflicts)
        raise SystemExit(f'Codex config already defines agentwork-managed role outside its managed block: {names}')

    newline = '\r\n' if '\r\n' in original else '\n'
    block = CODEX_CONFIG_BLOCK.read_text(encoding='utf-8').rstrip('\n').replace('\n', newline)
    if had_block:
        start_idx = original.find(CODEX_CONFIG_BLOCK_START)
        end_idx = original.find(CODEX_CONFIG_BLOCK_END) + len(CODEX_CONFIG_BLOCK_END)
        updated = original[:start_idx] + block + original[end_idx:]
    else:
        updated = original
        if updated and not updated.endswith(('\n', '\r')):
            updated += newline
        if updated:
            updated += newline
        updated += block + newline
    try:
        tomllib.loads(updated)
    except tomllib.TOMLDecodeError as exc:
        raise SystemExit(f'generated Codex config is invalid: {exc}') from exc
    return config, updated.encode('utf-8')


def parse_block(block_text: str):
    start_match = re.search(r'<!--\s*AGENTWORK:[^>]+:START\s*-->', block_text)
    end_match = re.search(r'<!--\s*AGENTWORK:[^>]+:END\s*-->', block_text)
    if not start_match or not end_match or start_match.start() >= end_match.start():
        raise SystemExit('bootstrap data block must contain one AGENTWORK START/END pair')
    return start_match.group(0), end_match.group(0), block_text[start_match.start():end_match.end()]


def prepare_block(target: Path, target_file: Path, block_file: Path, default_scaffold: str) -> PreparedFile:
    reject_symlink_path(target_file, target, 'managed data block')
    if target_file.exists() and not target_file.is_file():
        raise SystemExit(f'cannot manage data block path: {target_file}')
    block_text = block_file.read_text(encoding='utf-8')
    start_marker, end_marker, block = parse_block(block_text)
    if target_file.exists():
        try:
            text = target_file.read_bytes().decode('utf-8')
        except UnicodeDecodeError as exc:
            raise SystemExit(f'cannot update non-UTF-8 managed data file: {target_file}') from exc
    else:
        text = default_scaffold.rstrip() + '\n\n'
    span = managed_block_span(text, start_marker, end_marker, f'managed data file {target_file}')
    if span is not None:
        start_idx, end_idx = span
        text = text[:start_idx] + block + text[end_idx:]
    else:
        if text and not text.endswith('\n'):
            text += '\n'
        text += block + '\n'
    return PreparedFile(target_file, text.encode('utf-8'))


def prepare_managed_indexes(target: Path) -> tuple[PreparedFile, ...]:
    return tuple(
        prepare_block(target, target / rel, block_file, scaffold)
        for rel, block_file, scaffold in BLOCK_TARGETS
    )


def write_prepared_file(prepared: PreparedFile) -> None:
    prepared.path.parent.mkdir(parents=True, exist_ok=True)
    prepared.path.write_bytes(prepared.content)


def write_managed_indexes(prepared: tuple[PreparedFile, ...]) -> None:
    for item in prepared:
        write_prepared_file(item)


def has_tmp_gitignore_rule(text: str) -> bool:
    return any(line.strip() in TMP_GITIGNORE_PATTERNS for line in text.splitlines())


def prepare_gitignore(target: Path) -> tuple[PreparedFile, str, bool]:
    gitignore = target / '.gitignore'
    reject_symlink_path(gitignore, target, '.gitignore')
    if gitignore.exists() and not gitignore.is_file():
        raise SystemExit(f'cannot manage .gitignore path: {gitignore}')
    if gitignore.exists():
        before = gitignore.read_bytes()
        try:
            text = before.decode('utf-8')
        except UnicodeDecodeError as exc:
            raise SystemExit(f'cannot update non-UTF-8 .gitignore: {gitignore}') from exc
    else:
        before = b''
        text = ''

    block = GITIGNORE_BLOCK + '\n'
    span = managed_block_span(
        text,
        GITIGNORE_BLOCK_START,
        GITIGNORE_BLOCK_END,
        f'.gitignore {gitignore}',
    )
    if span is not None:
        start_idx, end_idx = span
        updated = text[:start_idx] + GITIGNORE_BLOCK + text[end_idx:]
        if updated and not updated.endswith('\n'):
            updated += '\n'
        content = updated.encode('utf-8')
        return PreparedFile(gitignore, content), 'updated managed .gitignore block', content != before

    if has_tmp_gitignore_rule(text):
        return PreparedFile(gitignore, before), 'kept existing .gitignore tmp rule', False

    if text and not text.endswith('\n'):
        text += '\n'
    if text:
        text += '\n'
    content = (text + block).encode('utf-8')
    return PreparedFile(gitignore, content), 'appended managed .gitignore tmp rule', True


def remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
        return
    if path.is_dir():
        shutil.rmtree(path)
        return
    if path.exists():
        raise OSError(f'unsupported transaction path: {path}')


def snapshot_path(path: Path, backup: Path) -> PathSnapshot:
    if path.is_symlink():
        raise OSError(f'refusing to snapshot symlink: {path}')
    if path.is_file():
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, backup)
        return PathSnapshot(path, 'file', backup)
    if path.is_dir():
        shutil.copytree(path, backup, symlinks=True)
        return PathSnapshot(path, 'directory', backup)
    if path.exists():
        raise OSError(f'unsupported transaction path: {path}')
    return PathSnapshot(path, 'missing', None)


def restore_snapshot(snapshot: PathSnapshot) -> None:
    remove_path(snapshot.path)
    if snapshot.kind == 'missing':
        return
    snapshot.path.parent.mkdir(parents=True, exist_ok=True)
    if snapshot.kind == 'file':
        shutil.copy2(snapshot.backup, snapshot.path)
        return
    if snapshot.kind == 'directory':
        shutil.copytree(snapshot.backup, snapshot.path, symlinks=True)
        return
    raise RuntimeError(f'unknown bootstrap snapshot kind: {snapshot.kind}')


def validate_transaction_path(target: Path, path: Path) -> None:
    if path == target or not path.is_relative_to(target):
        raise SystemExit(f'bootstrap transaction path must be below project root: {path}')
    current = path.parent
    while current != target:
        if current.is_symlink():
            raise SystemExit(f'bootstrap transaction path contains symlink: {current}')
        if current.exists() and not current.is_dir():
            raise SystemExit(f'bootstrap transaction parent is not a directory: {current}')
        current = current.parent


def collect_transaction_paths(target: Path, paths: list[Path]) -> tuple[Path, ...]:
    unique = tuple(dict.fromkeys(paths))
    for path in unique:
        validate_transaction_path(target, path)
    for index, path in enumerate(unique):
        for other in unique[index + 1:]:
            if path in other.parents or other in path.parents:
                raise SystemExit(f'overlapping bootstrap transaction paths: {path}, {other}')
    return unique


def new_parent_paths(target: Path, paths: tuple[Path, ...]) -> tuple[Path, ...]:
    missing: set[Path] = set()
    if not target.exists():
        missing.add(target)
    for path in paths:
        current = path.parent
        while current != target:
            if not current.exists():
                missing.add(current)
            current = current.parent
    return tuple(sorted(missing, key=lambda item: len(item.parts), reverse=True))


def run_transaction(target: Path, paths: tuple[Path, ...], operation: Callable[[], None]) -> None:
    new_parents = new_parent_paths(target, paths)
    with tempfile.TemporaryDirectory(prefix='agentwork-bootstrap-rollback-') as temp:
        backup_root = Path(temp)
        try:
            snapshots = tuple(
                snapshot_path(path, backup_root / str(index))
                for index, path in enumerate(paths)
            )
        except (OSError, shutil.Error) as exc:
            raise SystemExit(f'cannot prepare bootstrap transaction backup: {exc}') from exc

        try:
            operation()
        except (Exception, KeyboardInterrupt) as exc:
            rollback_errors: list[str] = []
            for snapshot in reversed(snapshots):
                try:
                    restore_snapshot(snapshot)
                except Exception as rollback_exc:
                    rollback_errors.append(f'{target_rel(target, snapshot.path)}: {rollback_exc}')
            for path in new_parents:
                try:
                    path.rmdir()
                except FileNotFoundError:
                    pass
                except OSError as rollback_exc:
                    if path.exists():
                        rollback_errors.append(
                            f'{target_rel(target, path)}: could not remove newly created directory: {rollback_exc}'
                        )
            if rollback_errors:
                details = '; '.join(rollback_errors)
                raise SystemExit(f'bootstrap transaction failed: {exc}; rollback incomplete: {details}') from exc
            raise SystemExit(f'bootstrap transaction failed and rolled back: {exc}') from exc


def target_rel(target: Path, path: Path) -> str:
    try:
        return str(path.relative_to(target))
    except ValueError:
        return str(path)


def prepare_bootstrap_plan(target: Path) -> BootstrapPlan:
    if target.exists() and not target.is_dir():
        raise SystemExit(f'project root must be a directory: {target}')
    writes = tuple(collect_writes(target))
    previous_receipt = load_receipt(target)
    preflight_writes(target, writes, previous_receipt)
    next_receipt = build_receipt(target, writes)
    config_path, config_content = prepare_codex_config(target)
    managed_indexes = prepare_managed_indexes(target)
    gitignore, gitignore_status, gitignore_changed = prepare_gitignore(target)
    retired_removed, retired_preserved = classify_retired_adapters(target)
    receipt = PreparedFile(receipt_path(target), next_receipt)

    transaction_paths = collect_transaction_paths(
        target,
        [
            *(dst for src, dst, _, _ in writes if src.resolve() != dst.resolve()),
            *(target / rel for rel in retired_removed),
            *(item.path for item in managed_indexes),
            config_path,
            *([gitignore.path] if gitignore_changed else []),
            receipt.path,
        ],
    )
    return BootstrapPlan(
        target=target,
        writes=writes,
        retired_removed=retired_removed,
        retired_preserved=retired_preserved,
        managed_indexes=managed_indexes,
        codex_config=PreparedFile(config_path, config_content),
        gitignore=gitignore,
        gitignore_status=gitignore_status,
        gitignore_changed=gitignore_changed,
        receipt=receipt,
        transaction_paths=transaction_paths,
    )


def apply_bootstrap_plan(plan: BootstrapPlan) -> None:
    target = plan.target
    print('== Removing retired adapters ==')
    remove_retired_adapters(target, plan.retired_removed)
    if plan.retired_removed:
        for rel in plan.retired_removed:
            print(f'- [remove-file] {rel}')
    else:
        print('- no agentwork-managed retired adapter files found')
    for rel in plan.retired_preserved:
        print(f'- [keep] {rel} (not recognized as agentwork-managed)')
    print()

    print('== Installing bootstrap ==')
    for src, dst, kind, label in plan.writes:
        if src.resolve() == dst.resolve():
            print(f'- [skip] {label}: {target_rel(target, dst)} (source==target)')
            continue
        copy_file(src, dst)
        print(f'- [{kind}] {label}: {target_rel(target, dst)}')
    print()

    print('== Updating managed data layer ==')
    write_managed_indexes(plan.managed_indexes)
    print('- refreshed managed project/session index blocks')
    write_prepared_file(plan.codex_config)
    print('- refreshed managed Codex agent registration block')
    if plan.gitignore_changed:
        write_prepared_file(plan.gitignore)
    print(f'- {plan.gitignore_status}')
    write_receipt(target, plan.receipt.content)
    print(f'- refreshed bootstrap receipt: {RECEIPT_REL}')
    print('- left existing local project/session files in place')
    print('- left existing installed tool files in place')


def main() -> int:
    parser = argparse.ArgumentParser(description='Install agentwork bootstrap into a target project, or refresh the source repo in place.')
    parser.add_argument('-p', '--project-root', required=True, help='target project root (required)')
    args = parser.parse_args()

    target = Path(args.project_root).resolve()
    if target == ROOT:
        prepare_bootstrap_plan(target)
        refresh_generated_bootstrap()
    plan = prepare_bootstrap_plan(target)
    run_transaction(
        target,
        plan.transaction_paths,
        lambda: apply_bootstrap_plan(plan),
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
