#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BOOTSTRAP = ROOT / '.agentwork' / 'bootstrap'
DATA = BOOTSTRAP / 'data'
SHARED_ROOT = ROOT / '.shared'
TOOLS_ROOT = ROOT / '.agentwork' / 'tools'
REGISTRY = TOOLS_ROOT / 'registry.json'

BLOCK_TARGETS = [
    (Path('.shared/project/index.md'), DATA / 'project-index.block.md', '# Project 索引\n\n## 本项目自定义内容\n'),
    (Path('.shared/session/README.md'), DATA / 'session-readme.block.md', '# Session 目录说明\n\n## 本项目补充说明\n'),
]
GITIGNORE_BLOCK_START = '# >>> AGENTWORK bootstrap: tmp artifacts >>>'
GITIGNORE_BLOCK_END = '# <<< AGENTWORK bootstrap: tmp artifacts <<<'
GITIGNORE_BLOCK = '\n'.join(
    [
        GITIGNORE_BLOCK_START,
        '.tmp/',
        GITIGNORE_BLOCK_END,
    ]
)
TMP_GITIGNORE_PATTERNS = {
    '.tmp',
    '.tmp/',
    '.tmp/*',
    '/.tmp',
    '/.tmp/',
    '/.tmp/*',
}
COPY_IGNORE = shutil.ignore_patterns('__pycache__', '*.pyc', '*.pyo')
AGENTWORK_BOOTSTRAP_MARKER = '<!-- AUTO-GENERATED by agentwork bootstrap -->'
RETIRED_BOOTSTRAP_PATHS = (
    Path('.agent/rules/bootstrap.md'),
    Path('.agent/workflows/brain.md'),
    Path('.agent/workflows/commit.md'),
    Path('.agent/workflows/exec.md'),
    Path('.agent/workflows/plan.md'),
    Path('.agent/workflows/review.md'),
    Path('.agent/workflows/session.md'),
    Path('.github/copilot-instructions.md'),
)
RETIRED_TOOL_SIGNATURES = {
    Path('.agent/skills/browser/SKILL.md'): ('# browser', '.shared/skills/browser/SKILL.md'),
    Path('.agent/workflows/android.md'): ('# /android', '.shared/commands/android.md'),
    Path('.agent/workflows/arch.md'): ('# /arch', '.shared/commands/arch.md'),
    Path('.agent/workflows/figma.md'): ('# /figma', '.shared/commands/figma.md'),
    Path('.agent/workflows/godot.md'): ('# /godot', '.shared/commands/godot.md'),
    Path('.github/prompts/android.instructions.md'): ('# Android Tool Instructions', '.shared/commands/android.md'),
    Path('.github/prompts/arch.instructions.md'): ('# Arch Tool Instructions', '.shared/commands/arch.md'),
    Path('.github/prompts/browser.instructions.md'): ('# Browser Tool Instructions', '.shared/skills/browser/SKILL.md'),
    Path('.github/prompts/figma.instructions.md'): ('# Figma Tool Instructions', '.shared/commands/figma.md'),
    Path('.github/prompts/godot.instructions.md'): ('# Godot Tool Instructions', '.shared/commands/godot.md'),
}
RETIRED_ADAPTER_PATHS = RETIRED_BOOTSTRAP_PATHS + tuple(RETIRED_TOOL_SIGNATURES)


def is_python_cache_artifact(rel: Path) -> bool:
    return '__pycache__' in rel.parts or rel.suffix in {'.pyc', '.pyo'}


def copy_file(src: Path, dst: Path) -> None:
    if src.resolve() == dst.resolve():
        return
    if dst.exists() and dst.is_dir():
        raise SystemExit(f'target path is a directory, expected file: {dst}')
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def copy_tree(src: Path, dst: Path) -> None:
    if src.resolve() == dst.resolve():
        return
    if dst.exists():
        if dst.is_symlink() or dst.is_file():
            raise SystemExit(f'target path is a file, expected directory: {dst}')
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=COPY_IGNORE)


def prune_empty_parents(path: Path, project_root: Path) -> None:
    current = path
    while current != project_root and current.exists():
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent


def is_agentwork_owned_retired_adapter(rel: Path, path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeError):
        return False
    if rel in RETIRED_BOOTSTRAP_PATHS:
        return AGENTWORK_BOOTSTRAP_MARKER in text
    signatures = RETIRED_TOOL_SIGNATURES.get(rel, ())
    return bool(signatures) and all(signature in text for signature in signatures)


def remove_retired_adapters(target: Path) -> tuple[list[Path], list[Path]]:
    removed = []
    preserved = []
    for rel in RETIRED_ADAPTER_PATHS:
        path = target / rel
        if not path.is_file() and not path.is_symlink():
            continue
        if not is_agentwork_owned_retired_adapter(rel, path):
            preserved.append(rel)
            continue
        path.unlink()
        prune_empty_parents(path.parent, target)
        removed.append(rel)
    return removed, preserved


def refresh_generated_bootstrap() -> None:
    renderer = BOOTSTRAP / 'render_bootstrap.py'
    if renderer.exists():
        subprocess.run([sys.executable, str(renderer)], check=True)


def load_tool_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding='utf-8'))


def is_path_covered(path: Path, declared_paths: set[Path]) -> bool:
    return any(path == declared or declared in path.parents for declared in declared_paths)


def collect_optional_shared_relpaths() -> set[Path]:
    relpaths: set[Path] = set()
    registry = load_tool_registry()
    for tool in registry.get('tools', []):
        tool_dir = TOOLS_ROOT / tool['dir']
        tool_meta = json.loads((tool_dir / 'tool.json').read_text(encoding='utf-8'))
        entries = tool_meta.get('entries', [])
        declared_sources = {
            Path(entry['from'])
            for entry in entries
            if entry.get('from', '').startswith('shared/') and entry.get('to', '').startswith('.shared/')
        }
        shared_dir = tool_dir / 'shared'
        missing = []
        if shared_dir.exists():
            missing = [
                path.relative_to(tool_dir)
                for path in sorted(shared_dir.rglob('*'))
                if path.is_file() and not is_path_covered(path.relative_to(tool_dir), declared_sources)
            ]
        if missing:
            details = ', '.join(str(path) for path in missing)
            raise SystemExit(f'optional tool shared files missing from tool.json entries ({tool_dir.name}): {details}')

        for entry in entries:
            target = entry.get('to', '')
            if target.startswith('.shared/'):
                relpaths.add(Path(target.removeprefix('.shared/')))
    return relpaths


def collect_core_shared_writes(target: Path):
    writes = []
    optional_shared_relpaths = collect_optional_shared_relpaths()
    for src in sorted(x for x in SHARED_ROOT.rglob('*') if x.is_file()):
        rel = src.relative_to(SHARED_ROOT)
        if is_python_cache_artifact(rel):
            continue
        if rel.parts and rel.parts[0] in {'project', 'session'}:
            continue
        if is_path_covered(rel, optional_shared_relpaths):
            continue
        writes.append((src, target / '.shared' / rel, 'file', 'core shared file'))
    return writes


def collect_writes(target: Path):
    writes = []
    writes.extend(collect_core_shared_writes(target))
    root_bootstrap = ROOT / 'AGENTS.md' if target.resolve() == ROOT.resolve() else BOOTSTRAP / 'root' / 'AGENTS.md'
    writes.append((root_bootstrap, target / 'AGENTS.md', 'file', 'root bootstrap file'))
    writes.append((BOOTSTRAP / 'claude' / 'CLAUDE.md', target / '.claude' / 'CLAUDE.md', 'file', 'Claude bootstrap file'))
    for src in sorted((BOOTSTRAP / 'claude' / 'commands').glob('*.md')):
        writes.append((src, target / '.claude' / 'commands' / src.name, 'file', 'Claude wrapper'))
    writes.append((BOOTSTRAP / 'cursor' / 'rules' / 'agentwork-bootstrap.mdc', target / '.cursor' / 'rules' / 'agentwork-bootstrap.mdc', 'file', 'Cursor rule'))
    for src in sorted((BOOTSTRAP / 'codex' / 'skills').iterdir()):
        if src.is_dir():
            writes.append((src, target / '.codex' / 'skills' / src.name, 'dir', 'Codex skill wrapper'))
    for src in sorted((BOOTSTRAP / 'opencode' / 'commands').glob('*.md')):
        writes.append((src, target / '.opencode' / 'commands' / src.name, 'file', 'OpenCode command wrapper'))
    opencode_gitignore = BOOTSTRAP / 'opencode' / '.gitignore'
    if opencode_gitignore.exists():
        writes.append((opencode_gitignore, target / '.opencode' / '.gitignore', 'file', 'OpenCode dir gitignore'))
    return writes


def parse_block(block_text: str):
    start_match = re.search(r'<!--\s*AGENTWORK:[^>]+:START\s*-->', block_text)
    end_match = re.search(r'<!--\s*AGENTWORK:[^>]+:END\s*-->', block_text)
    if not start_match or not end_match or start_match.start() >= end_match.start():
        raise SystemExit('bootstrap data block must contain one AGENTWORK START/END pair')
    return start_match.group(0), end_match.group(0), block_text[start_match.start():end_match.end()]


def upsert_block(target_file: Path, block_file: Path, default_scaffold: str) -> None:
    block_text = block_file.read_text(encoding='utf-8')
    start_marker, end_marker, block = parse_block(block_text)
    if target_file.exists():
        text = target_file.read_text(encoding='utf-8')
    else:
        text = default_scaffold.rstrip() + '\n\n'
    start_idx = text.find(start_marker)
    end_idx = text.find(end_marker)
    if start_idx != -1 and end_idx != -1 and start_idx < end_idx:
        end_idx += len(end_marker)
        text = text[:start_idx] + block + text[end_idx:]
    else:
        if text and not text.endswith('\n'):
            text += '\n'
        text += block + '\n'
    target_file.parent.mkdir(parents=True, exist_ok=True)
    target_file.write_text(text, encoding='utf-8')


def update_managed_indexes(target: Path) -> None:
    (target / '.shared' / 'project').mkdir(parents=True, exist_ok=True)
    (target / '.shared' / 'session').mkdir(parents=True, exist_ok=True)
    for rel, block_file, scaffold in BLOCK_TARGETS:
        upsert_block(target / rel, block_file, scaffold)


def has_tmp_gitignore_rule(text: str) -> bool:
    return any(line.strip() in TMP_GITIGNORE_PATTERNS for line in text.splitlines())


def upsert_gitignore(target: Path) -> str:
    gitignore = target / '.gitignore'
    if gitignore.exists():
        text = gitignore.read_text(encoding='utf-8')
    else:
        text = ''

    block = GITIGNORE_BLOCK + '\n'
    start_idx = text.find(GITIGNORE_BLOCK_START)
    end_idx = text.find(GITIGNORE_BLOCK_END)
    if start_idx != -1 and end_idx != -1 and start_idx < end_idx:
        end_idx += len(GITIGNORE_BLOCK_END)
        updated = text[:start_idx] + GITIGNORE_BLOCK + text[end_idx:]
        if updated and not updated.endswith('\n'):
            updated += '\n'
        gitignore.write_text(updated, encoding='utf-8')
        return 'updated managed .gitignore block'

    if has_tmp_gitignore_rule(text):
        return 'kept existing .gitignore tmp rule'

    if text and not text.endswith('\n'):
        text += '\n'
    if text:
        text += '\n'
    gitignore.write_text(text + block, encoding='utf-8')
    return 'appended managed .gitignore tmp rule'


def target_rel(target: Path, path: Path) -> str:
    try:
        return str(path.relative_to(target))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(description='Install agentwork bootstrap into a target project, or refresh the source repo in place.')
    parser.add_argument('-p', '--project-root', required=True, help='target project root (required)')
    args = parser.parse_args()

    refresh_generated_bootstrap()
    target = Path(args.project_root).resolve()
    writes = collect_writes(target)

    print('== Removing retired adapters ==')
    removed, preserved = remove_retired_adapters(target)
    if removed:
        for rel in removed:
            print(f'- [remove-file] {rel}')
    else:
        print('- no agentwork-managed retired adapter files found')
    for rel in preserved:
        print(f'- [keep] {rel} (not recognized as agentwork-managed)')
    print()

    print('== Installing bootstrap ==')
    for src, dst, kind, label in writes:
        if src.resolve() == dst.resolve():
            print(f'- [skip] {label}: {target_rel(target, dst)} (source==target)')
            continue
        if kind == 'dir':
            copy_tree(src, dst)
        else:
            copy_file(src, dst)
        print(f'- [{kind}] {label}: {target_rel(target, dst)}')
    print()
    print('== Updating managed data layer ==')
    update_managed_indexes(target)
    print('- refreshed managed project/session index blocks')
    print(f'- {upsert_gitignore(target)}')
    print('- left existing local project/session files in place')
    print('- left existing installed tool files in place')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
