#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

BOOTSTRAP = Path(__file__).resolve().parent
ROOT = BOOTSTRAP.parent.parent
SPEC = json.loads((BOOTSTRAP / 'spec.json').read_text(encoding='utf-8'))
COMMON = SPEC['common']
DATA = BOOTSTRAP / 'data'
AUTO = '<!-- AUTO-GENERATED by agentwork bootstrap -->'
CODEX_AUTO = '# AUTO-GENERATED by agentwork bootstrap'
CODEX_CONFIG_START = '# >>> AGENTWORK bootstrap: Codex agents >>>'
CODEX_CONFIG_END = '# <<< AGENTWORK bootstrap: Codex agents <<<'


def bullet(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def number(items: list[str]) -> str:
    return "\n".join(f"{i}. {item}" for i, item in enumerate(items, 1))


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_memory(kind: str) -> str:
    v = SPEC['variants'][kind]
    out: list[str] = [AUTO, v['title'], '']
    if v['intro']:
        out += [v['intro'], '']
    out += [COMMON['repo_intro'], '', f"> {COMMON['warning']}"]
    if v['note']:
        out += ['', f"> {v['note']}"]
    out += [
        '', COMMON['safety_title'], '', COMMON['danger_intro'], '', bullet(COMMON['danger_items']), '', COMMON['self_fix'],
        '', COMMON['startup_title'], number(COMMON['startup_items']),
        '', COMMON['basic_title'], bullet(COMMON['basic_items']),
    ]
    extra_basic = v.get('extra_basic') or []
    if extra_basic:
        out += [bullet(extra_basic)]
    out += [
        '', COMMON['workflow_title'], '', bullet(COMMON['workflow_items']),
        '', COMMON['complex_title'], '', bullet(COMMON['complex_items'])
    ]
    extra_complex = v.get('extra_complex') or []
    if extra_complex:
        out += [bullet(extra_complex)]
    out += ['', COMMON['navigation_title'], '', bullet(COMMON['navigation_items'])]
    return "\n".join(out).rstrip() + "\n"


def render_cursor() -> str:
    v = SPEC['variants']['cursor']
    body = [
        AUTO,
        v['title'],
        '',
        v['intro'],
        '',
        COMMON['repo_intro'],
        '',
        f"> {v['note']}",
        '',
        COMMON['basic_title'],
        bullet(COMMON['basic_items']),
        '',
        COMMON['workflow_title'],
        '',
        bullet(COMMON['workflow_items']),
        '',
        COMMON['navigation_title'],
        '',
        bullet(COMMON['navigation_items']),
    ]
    return "\n".join(body).rstrip() + "\n"


def render_claude_command(title: str, target: str) -> str:
    return (
        f"{AUTO}\n# {title}\n\n"
        "命令入口，读取共享规则。\n\n"
        "## 执行前必读\n"
        f"- 主定义：`{target}`\n"
        "- 占位符规范：`.shared/constraints/placeholder-naming.md`\n"
    )


def render_codex_skill(
    name: str,
    title: str,
    target: str,
    interaction: list[str] | None = None,
) -> str:
    out = (
        f"---\nname: {name}\ndescription: {title} 命令入口\n---\n\n"
        f"{AUTO}\n"
        f"# {title}\n\n"
        "命令入口，读取共享规则。\n\n"
        "## 执行前必读\n"
        f"- 主定义：`{target}`\n"
        "- 占位符规范：`.shared/constraints/placeholder-naming.md`\n"
    )
    if interaction:
        out += f"\n## Codex 交互适配\n{bullet(interaction)}\n"
    return out


def validate_codex_agent(agent: dict) -> None:
    name = agent['name']
    filename = agent['file']
    if not re.fullmatch(r'[A-Za-z0-9_-]+', name):
        raise SystemExit(f'invalid Codex agent name: {name}')
    if Path(filename).name != filename or not filename.endswith('.toml'):
        raise SystemExit(f'invalid Codex agent filename: {filename}')


def render_codex_agent(agent: dict) -> str:
    validate_codex_agent(agent)
    instructions = "\n".join(agent['developer_instructions']).rstrip()
    if '"""' in instructions:
        raise SystemExit(f'Codex agent instructions contain unsupported triple quote: {agent["name"]}')
    instructions = instructions.replace('\\', '\\\\')
    return (
        f"{CODEX_AUTO}\n"
        f"model = {toml_string(agent['model'])}\n"
        f"model_reasoning_effort = {toml_string(agent['model_reasoning_effort'])}\n\n"
        f"developer_instructions = \"\"\"\n{instructions}\n\"\"\"\n"
    )


def render_codex_config_block() -> str:
    out = [CODEX_CONFIG_START, CODEX_AUTO]
    for index, agent in enumerate(SPEC['codex_agents']):
        validate_codex_agent(agent)
        if index:
            out.append('')
        out += [
            f"[agents.{agent['name']}]",
            f"description = {toml_string(agent['description'])}",
            f"config_file = {toml_string('agents/' + agent['file'])}",
        ]
    out += [CODEX_CONFIG_END]
    return "\n".join(out) + "\n"


def render_opencode_command(title: str, target: str) -> str:
    return (
        f"---\ndescription: {title} 命令入口\n---\n\n"
        f"{AUTO}\n"
        f"# {title}\n\n"
        "按共享定义执行本命令，参数如下（可为空）：\n\n"
        "$ARGUMENTS\n\n"
        "## 执行前必读\n"
        f"@{target}\n"
        "@.shared/constraints/placeholder-naming.md\n"
    )


def parse_block(block_text: str):
    start = re.search(r'<!--\s*AGENTWORK:[^>]+:START\s*-->', block_text)
    end = re.search(r'<!--\s*AGENTWORK:[^>]+:END\s*-->', block_text)
    if not start or not end or start.start() >= end.start():
        raise SystemExit('invalid bootstrap data block')
    return start.group(0), end.group(0), block_text[start.start():end.end()]


def managed_block_span(
    text: str,
    start_marker: str,
    end_marker: str,
    label: str,
) -> tuple[int, int] | None:
    start_count = text.count(start_marker)
    end_count = text.count(end_marker)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise SystemExit(f'{label} has a malformed or duplicate agentwork managed block')
    start_idx = text.find(start_marker)
    end_idx = text.find(end_marker)
    if start_idx >= end_idx:
        raise SystemExit(f'{label} has an invalid agentwork managed block')
    return start_idx, end_idx + len(end_marker)


def prepare_block(target_file: Path, block_file: Path, scaffold: str) -> tuple[Path, str]:
    block_text = block_file.read_text(encoding='utf-8')
    start_marker, end_marker, block = parse_block(block_text)
    if target_file.exists():
        try:
            text = target_file.read_bytes().decode('utf-8')
        except UnicodeDecodeError as exc:
            raise SystemExit(f'cannot update non-UTF-8 managed data file: {target_file}') from exc
    else:
        text = scaffold.rstrip() + "\n\n"
    span = managed_block_span(text, start_marker, end_marker, f'managed data file {target_file}')
    if span is not None:
        start_idx, end_idx = span
        text = text[:start_idx] + block + text[end_idx:]
    else:
        if text and not text.endswith("\n"):
            text += "\n"
        text += block + "\n"
    return target_file, text


def prepare_root_shared_data() -> tuple[tuple[Path, str], ...]:
    return (
        prepare_block(
            ROOT / '.shared/project/index.md',
            DATA / 'project-index.block.md',
            '# Project 索引\n\n## 本项目自定义内容\n',
        ),
        prepare_block(
            ROOT / '.shared/session/README.md',
            DATA / 'session-readme.block.md',
            '# Session 目录说明\n\n## 本项目补充说明\n',
        ),
    )


def write_prepared_blocks(prepared: tuple[tuple[Path, str], ...]) -> None:
    for target_file, text in prepared:
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(text, encoding='utf-8')


def main() -> int:
    root_shared_data = prepare_root_shared_data()
    (BOOTSTRAP / 'root').mkdir(parents=True, exist_ok=True)
    (BOOTSTRAP / 'claude' / 'commands').mkdir(parents=True, exist_ok=True)
    (BOOTSTRAP / 'opencode' / 'commands').mkdir(parents=True, exist_ok=True)
    (ROOT / 'AGENTS.md').write_text(render_memory('source_root'), encoding='utf-8')
    write_prepared_blocks(root_shared_data)
    (BOOTSTRAP / 'root' / 'AGENTS.md').write_text(render_memory('target_root'), encoding='utf-8')
    (BOOTSTRAP / 'claude' / 'CLAUDE.md').write_text(render_memory('claude'), encoding='utf-8')
    (BOOTSTRAP / 'cursor' / 'rules').mkdir(parents=True, exist_ok=True)
    (BOOTSTRAP / 'cursor' / 'rules' / 'agentwork-bootstrap.mdc').write_text(render_cursor(), encoding='utf-8')
    codex_agents = BOOTSTRAP / 'codex' / 'agents'
    codex_agents.mkdir(parents=True, exist_ok=True)
    for agent in SPEC['codex_agents']:
        (codex_agents / agent['file']).write_text(render_codex_agent(agent), encoding='utf-8')
    (BOOTSTRAP / 'codex' / 'config.block.toml').write_text(render_codex_config_block(), encoding='utf-8')
    for wrapper in SPEC['wrappers']:
        name = wrapper['name']
        title = wrapper['title']
        target = wrapper['target']
        (BOOTSTRAP / 'claude' / 'commands' / f'{name}.md').write_text(render_claude_command(title, target), encoding='utf-8')
        skill_dir = BOOTSTRAP / 'codex' / 'skills' / name
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / 'SKILL.md').write_text(
            render_codex_skill(name, title, target, wrapper.get('codex_interaction')),
            encoding='utf-8',
        )
        (BOOTSTRAP / 'opencode' / 'commands' / f'{name}.md').write_text(
            render_opencode_command(title, target),
            encoding='utf-8',
        )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
