#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
import argparse
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

BOOTSTRAP = Path(__file__).resolve().parent
ROOT = BOOTSTRAP.parent.parent
SPEC = json.loads((BOOTSTRAP / 'spec.json').read_text(encoding='utf-8'))
COMMON = SPEC['common']
DATA = BOOTSTRAP / 'data'
AUTO = '<!-- AUTO-GENERATED by agentwork bootstrap -->'
CODEX_AUTO = '# AUTO-GENERATED by agentwork bootstrap'
CODEX_CONFIG_START = '# >>> AGENTWORK bootstrap: Codex agents >>>'
CODEX_CONFIG_END = '# <<< AGENTWORK bootstrap: Codex agents <<<'
WRAPPER_NAME_PATTERN = re.compile(r'[a-z0-9]+(?:-[a-z0-9]+)*\Z')
PI_NAME_PATTERN = WRAPPER_NAME_PATTERN


@dataclass(frozen=True)
class RenderedFile:
    path: Path
    content: bytes


@dataclass(frozen=True)
class RenderSnapshot:
    path: Path
    backup: Path | None


def bullet(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def number(items: list[str]) -> str:
    return "\n".join(f"{i}. {item}" for i, item in enumerate(items, 1))


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def default_wrapper_description(title: str) -> str:
    """Fallback description for a wrapper that declares none.

    Shared by the Pi metadata path and the platform render loop so both
    default identically; drifting defaults would give Pi a different
    description than Claude, Codex and OpenCode for the same command.
    """
    return f'{title} 命令入口'


def render_memory(kind: str) -> str:
    v = SPEC['variants'][kind]
    out: list[str] = [AUTO, v['title'], '']
    if v['intro']:
        out += [v['intro'], '']
    out += [COMMON['repo_intro'], '', f"> {COMMON['warning']}"]
    if v['note']:
        out += ['', f"> {v['note']}"]
    out += [
        '', COMMON['safety_title'], '', COMMON['danger_intro'], '', bullet(COMMON['danger_items']), '', COMMON['self_fix'],
        '', COMMON['startup_title'], number(COMMON['startup_items']),
        '', COMMON['basic_title'], bullet(COMMON['basic_items']),
    ]
    extra_basic = v.get('extra_basic') or []
    if extra_basic:
        out += [bullet(extra_basic)]
    out += [
        '', COMMON['workflow_title'], '', bullet(COMMON['workflow_items']),
        '', COMMON['complex_title'], '', bullet(COMMON['complex_items'])
    ]
    extra_complex = v.get('extra_complex') or []
    if extra_complex:
        out += [bullet(extra_complex)]
    out += ['', COMMON['navigation_title'], '', bullet(COMMON['navigation_items'])]
    return "\n".join(out).rstrip() + "\n"


def render_cursor() -> str:
    v = SPEC['variants']['cursor']
    workflow_items = v.get('workflow_override') or COMMON['workflow_items']
    body = [
        v['title'],
        '',
        AUTO,
        '',
        v['intro'],
        '',
        COMMON['repo_intro'],
        '',
        f"> {v['note']}",
        '',
        COMMON['startup_title'],
        number(COMMON['startup_items']),
        '',
        COMMON['basic_title'],
        bullet(COMMON['basic_items']),
        '',
        COMMON['workflow_title'],
        '',
        bullet(workflow_items),
        '',
        COMMON['navigation_title'],
        '',
        bullet(COMMON['navigation_items']),
    ]
    return "\n".join(body).rstrip() + "\n"


def render_claude_command(title: str, description: str, target: str) -> str:
    return (
        f"---\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
        f"{AUTO}\n# {title}\n\n"
        "命令入口，读取共享规则。\n\n"
        "## 执行前必读\n"
        f"- 主定义：`{target}`\n"
    )


def render_codex_skill(
    name: str,
    title: str,
    description: str,
    target: str,
    interaction: list[str] | None = None,
) -> str:
    out = (
        f"---\nname: {name}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
        f"{AUTO}\n"
        f"# {title}\n\n"
        "命令入口，读取共享规则。\n\n"
        "## 执行前必读\n"
        f"- 主定义：`{target}`\n"
    )
    if interaction:
        out += f"\n## Codex 交互适配\n{bullet(interaction)}\n"
    return out


def validate_codex_agent(agent: dict) -> None:
    name = agent['name']
    filename = agent['file']
    if not re.fullmatch(r'[A-Za-z0-9_-]+', name):
        raise SystemExit(f'invalid Codex agent name: {name}')
    if Path(filename).name != filename or not filename.endswith('.toml'):
        raise SystemExit(f'invalid Codex agent filename: {filename}')


def render_codex_agent(agent: dict) -> str:
    validate_codex_agent(agent)
    instructions = "\n".join(agent['developer_instructions']).rstrip()
    if '"""' in instructions:
        raise SystemExit(f'Codex agent instructions contain unsupported triple quote: {agent["name"]}')
    instructions = instructions.replace('\\', '\\\\')
    return (
        f"{CODEX_AUTO}\n"
        f"model = {toml_string(agent['model'])}\n"
        f"model_reasoning_effort = {toml_string(agent['model_reasoning_effort'])}\n\n"
        f"developer_instructions = \"\"\"\n{instructions}\n\"\"\"\n"
    )


def render_codex_config_block() -> str:
    out = [CODEX_CONFIG_START, CODEX_AUTO]
    for index, agent in enumerate(SPEC['codex_agents']):
        validate_codex_agent(agent)
        if index:
            out.append('')
        out += [
            f"[agents.{agent['name']}]",
            f"description = {toml_string(agent['description'])}",
            f"config_file = {toml_string('agents/' + agent['file'])}",
        ]
    out += [CODEX_CONFIG_END]
    return "\n".join(out) + "\n"


def render_opencode_command(title: str, description: str, target: str) -> str:
    return (
        f"---\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
        f"{AUTO}\n"
        f"# {title}\n\n"
        "按共享定义执行本命令，参数如下（可为空）：\n\n"
        "$ARGUMENTS\n\n"
        "## 执行前必读\n"
        f"@{target}\n"
    )


def validate_shared_command_target(target: object, *, label: str) -> str:
    if not isinstance(target, str):
        raise SystemExit(f'invalid {label} target: {target!r}')
    target_path = Path(target)
    if (
        target_path.is_absolute()
        or target_path.as_posix() != target
        or target_path.parent != Path('.shared/commands')
        or target_path.suffix != '.md'
        or '\n' in target
        or '\r' in target
        or any(part in {'', '.', '..'} for part in target_path.parts)
    ):
        raise SystemExit(f'invalid {label} target: {target}')

    target_file = ROOT / target_path
    current = target_file
    while current != ROOT:
        if current.is_symlink():
            raise SystemExit(f'{label} target contains symlink: {current}')
        current = current.parent

    try:
        root = ROOT.resolve()
        command_root = (ROOT / '.shared' / 'commands').resolve()
        command_root.relative_to(root)
        resolved = target_file.resolve(strict=False)
        resolved.relative_to(command_root)
    except (OSError, RuntimeError, ValueError) as exc:
        raise SystemExit(f'{label} target escapes shared commands: {target}') from exc
    if resolved != target_file:
        raise SystemExit(f'{label} target is not canonical: {target}')
    if not target_file.is_file():
        raise SystemExit(f'{label} target does not exist: {target}')
    return target


def validated_wrapper_specs(raw_wrappers: object | None = None) -> tuple[dict, ...]:
    wrappers = SPEC.get('wrappers') if raw_wrappers is None else raw_wrappers
    if not isinstance(wrappers, (list, tuple)):
        raise SystemExit('invalid bootstrap wrapper specification')
    seen: set[str] = set()
    result: list[dict] = []
    for wrapper in wrappers:
        if not isinstance(wrapper, dict):
            raise SystemExit('invalid bootstrap wrapper specification')
        name = wrapper.get('name')
        if not isinstance(name, str) or not WRAPPER_NAME_PATTERN.fullmatch(name):
            raise SystemExit(f'invalid bootstrap wrapper name: {name!r}')
        folded = name.casefold()
        if folded in seen:
            raise SystemExit(f'duplicate bootstrap wrapper name: {name}')
        seen.add(folded)

        title = wrapper.get('title')
        if not isinstance(title, str) or '\n' in title or '\r' in title:
            raise SystemExit(f'invalid bootstrap wrapper title: {name}')
        prefix = f'/{name}'
        if title != prefix and not title.startswith(prefix + ' '):
            raise SystemExit(f'bootstrap wrapper title does not match its command name: {name}')
        validate_shared_command_target(wrapper.get('target'), label=f'bootstrap wrapper {name}')

        interaction = wrapper.get('codex_interaction')
        if interaction is not None and (
            not isinstance(interaction, list)
            or not all(
                isinstance(item, str) and '\n' not in item and '\r' not in item
                for item in interaction
            )
        ):
            raise SystemExit(f'invalid Codex interaction metadata: {name}')

        description = wrapper.get('description')
        if description is not None and (
            not isinstance(description, str)
            or not description.strip()
            or '\n' in description
            or '\r' in description
        ):
            raise SystemExit(f'invalid bootstrap wrapper description: {name}')
        result.append(wrapper)
    return tuple(result)


def validated_pi_wrappers(
    wrappers: tuple[dict, ...] | None = None,
) -> tuple[dict, ...]:
    pi = SPEC.get('pi')
    if not isinstance(pi, dict):
        raise SystemExit('missing Pi bootstrap configuration')
    baseline = pi.get('compatibility_baseline')
    if not isinstance(baseline, str) or not re.fullmatch(r'\d+\.\d+\.\d+', baseline):
        raise SystemExit('invalid Pi compatibility baseline')
    tag_commit = pi.get('tag_commit')
    if not isinstance(tag_commit, str) or not re.fullmatch(r'[0-9a-f]{40}', tag_commit):
        raise SystemExit('invalid Pi compatibility tag commit')
    reserved = pi.get('tui_reserved_commands')
    if not isinstance(reserved, list) or not all(isinstance(name, str) for name in reserved):
        raise SystemExit('invalid Pi TUI reserved command list')
    if reserved != sorted(set(reserved)) or any(not PI_NAME_PATTERN.fullmatch(name) for name in reserved):
        raise SystemExit('Pi TUI reserved commands must be unique sorted lowercase ASCII names')

    wrapper_specs = validated_wrapper_specs(wrappers)
    seen: set[str] = set()
    result: list[dict] = []
    for wrapper in wrapper_specs:
        name = wrapper.get('pi_name', wrapper.get('name'))
        if not isinstance(name, str) or not PI_NAME_PATTERN.fullmatch(name):
            raise SystemExit(f'invalid Pi prompt name: {name!r}')
        folded = name.casefold()
        if folded in seen:
            raise SystemExit(f'duplicate Pi prompt name: {name}')
        seen.add(folded)
        if name in reserved:
            raise SystemExit(f'Pi prompt name conflicts with v{baseline} TUI command: {name}')

        title = wrapper.get('pi_title', wrapper.get('title'))
        description = wrapper.get(
            'pi_description',
            wrapper.get('description', default_wrapper_description(title)),
        )
        if not isinstance(title, str) or not isinstance(description, str):
            raise SystemExit(f'invalid Pi prompt metadata: {name}')
        if '\n' in title or '\r' in title or '\n' in description or '\r' in description:
            raise SystemExit(f'Pi prompt metadata contains a newline: {name}')
        prefix = f'/{name}'
        if title == prefix:
            argument_hint = None
        elif title.startswith(prefix + ' '):
            argument_hint = title[len(prefix) + 1:]
        else:
            raise SystemExit(f'Pi prompt title does not match its command name: {name}')

        target = validate_shared_command_target(wrapper.get('target'), label=f'Pi prompt {name}')
        result.append(
            {
                'name': name,
                'title': title,
                'description': description,
                'argument_hint': argument_hint,
                'target': target,
            }
        )
    return tuple(result)


def render_pi_prompt(wrapper: dict) -> str:
    frontmatter = [
        '---',
        f"description: {json.dumps(wrapper['description'], ensure_ascii=False)}",
    ]
    if wrapper['argument_hint']:
        frontmatter.append(
            f"argument-hint: {json.dumps(wrapper['argument_hint'], ensure_ascii=False)}"
        )
    frontmatter += ['---', '']
    body = [
        AUTO,
        f"# {wrapper['title']}",
        '',
        '按共享定义执行本命令。Pi 会按 prompt template 规则展开以下用户参数（可为空）：',
        '',
        '$ARGUMENTS',
        '',
        '## 执行前必读',
        f"- 完整读取主定义：`{wrapper['target']}`",
    ]
    return "\n".join([*frontmatter, *body]).rstrip() + "\n"


def parse_block(block_text: str):
    start = re.search(r'<!--\s*AGENTWORK:[^>]+:START\s*-->', block_text)
    end = re.search(r'<!--\s*AGENTWORK:[^>]+:END\s*-->', block_text)
    if not start or not end or start.start() >= end.start():
        raise SystemExit('invalid bootstrap data block')
    return start.group(0), end.group(0), block_text[start.start():end.end()]


def managed_block_span(
    text: str,
    start_marker: str,
    end_marker: str,
    label: str,
) -> tuple[int, int] | None:
    start_count = text.count(start_marker)
    end_count = text.count(end_marker)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise SystemExit(f'{label} has a malformed or duplicate agentwork managed block')
    start_idx = text.find(start_marker)
    end_idx = text.find(end_marker)
    if start_idx >= end_idx:
        raise SystemExit(f'{label} has an invalid agentwork managed block')
    return start_idx, end_idx + len(end_marker)


def prepare_block(target_file: Path, block_file: Path, scaffold: str) -> tuple[Path, str]:
    block_text = block_file.read_text(encoding='utf-8')
    start_marker, end_marker, block = parse_block(block_text)
    if target_file.exists():
        try:
            text = target_file.read_bytes().decode('utf-8')
        except UnicodeDecodeError as exc:
            raise SystemExit(f'cannot update non-UTF-8 managed data file: {target_file}') from exc
    else:
        text = scaffold.rstrip() + "\n\n"
    span = managed_block_span(text, start_marker, end_marker, f'managed data file {target_file}')
    if span is not None:
        start_idx, end_idx = span
        text = text[:start_idx] + block + text[end_idx:]
    else:
        if text and not text.endswith("\n"):
            text += "\n"
        text += block + "\n"
    return target_file, text


def prepare_root_shared_data() -> tuple[tuple[Path, str], ...]:
    return (
        prepare_block(
            ROOT / '.shared/project/index.md',
            DATA / 'project-index.block.md',
            '# Project 索引\n\n## 本项目自定义内容\n',
        ),
        prepare_block(
            ROOT / '.shared/case/README.md',
            DATA / 'case-readme.block.md',
            '# Case 目录说明\n\n## 本项目补充说明\n',
        ),
    )


def render_capability_rule(description: str, body: str) -> str:
    return f'---\ndescription: {description}\nglobs: []\nalwaysApply: false\n---\n\n{body}\n'


def safe_spec_relpath(value: object, field: str) -> Path:
    if not isinstance(value, str) or not value:
        raise SystemExit(f'invalid bootstrap default capability {field}')
    path = Path(value)
    if path.is_absolute() or '..' in path.parts:
        raise SystemExit(f'invalid bootstrap default capability {field}: {value}')
    return path


def validated_default_capabilities() -> tuple[dict, ...]:
    raw = SPEC.get('default_capabilities')
    if not isinstance(raw, list) or not raw:
        raise SystemExit('invalid bootstrap default capability specification')
    seen: set[str] = set()
    for capability in raw:
        if not isinstance(capability, dict) or set(capability) != {
            'name', 'canonical', 'mirror_to', 'cursor_rule'
        }:
            raise SystemExit('invalid bootstrap default capability specification')
        name = capability['name']
        if not isinstance(name, str) or not WRAPPER_NAME_PATTERN.fullmatch(name):
            raise SystemExit(f'invalid bootstrap default capability name: {name!r}')
        if name in seen:
            raise SystemExit(f'duplicate bootstrap default capability: {name}')
        seen.add(name)
        safe_spec_relpath(capability['canonical'], f'{name} canonical')
        mirrors = capability['mirror_to']
        if not isinstance(mirrors, list) or not mirrors:
            raise SystemExit(f'{name}: default capability mirror_to must be a non-empty list')
        for mirror in mirrors:
            safe_spec_relpath(mirror, f'{name} mirror_to')
        rule = capability['cursor_rule']
        if not isinstance(rule, dict) or set(rule) != {'path', 'description', 'body'}:
            raise SystemExit(f'{name}: invalid default capability cursor_rule')
        safe_spec_relpath(rule['path'], f'{name} cursor_rule path')
        for field in ('description', 'body'):
            if not isinstance(rule[field], str) or not rule[field].strip():
                raise SystemExit(f'{name}: default capability cursor_rule {field} must be non-empty')
    return tuple(raw)


def add_rendered_file(outputs: dict[Path, bytes], path: Path, text: str) -> None:
    if path in outputs:
        raise SystemExit(f'duplicate bootstrap render target: {path}')
    outputs[path] = text.encode('utf-8')


def prepare_rendered_bootstrap() -> tuple[RenderedFile, ...]:
    wrappers = validated_wrapper_specs()
    pi_wrappers = validated_pi_wrappers(wrappers)
    default_capabilities = validated_default_capabilities()
    root_shared_data = prepare_root_shared_data()
    outputs: dict[Path, bytes] = {}
    add_rendered_file(outputs, ROOT / 'AGENTS.md', render_memory('source_root'))
    for path, text in root_shared_data:
        add_rendered_file(outputs, path, text)
    add_rendered_file(outputs, BOOTSTRAP / 'root' / 'AGENTS.md', render_memory('target_root'))
    add_rendered_file(outputs, BOOTSTRAP / 'claude' / 'CLAUDE.md', render_memory('claude'))
    add_rendered_file(
        outputs,
        BOOTSTRAP / 'cursor' / 'rules' / 'agentwork-bootstrap.mdc',
        render_cursor(),
    )
    # 默认能力的正文随 bootstrap 分发，运行时依赖仍按项目延迟安装。
    # canonical 源优先；测试夹具与外部 bootstrap checkout 可能只含 bootstrap 树，
    # 故回退到第一个 mirror 目标，保持自包含。
    for capability in default_capabilities:
        mirrors = [BOOTSTRAP / Path(mirror) for mirror in capability['mirror_to']]
        source = ROOT / Path(capability['canonical'])
        if not source.is_file():
            source = mirrors[0]
        skill = source.read_text(encoding='utf-8')
        for mirror in mirrors:
            add_rendered_file(outputs, mirror, skill)
        rule = capability['cursor_rule']
        add_rendered_file(
            outputs,
            BOOTSTRAP / Path(rule['path']),
            render_capability_rule(rule['description'], rule['body']),
        )
    for agent in SPEC['codex_agents']:
        add_rendered_file(
            outputs,
            BOOTSTRAP / 'codex' / 'agents' / agent['file'],
            render_codex_agent(agent),
        )
    add_rendered_file(
        outputs,
        BOOTSTRAP / 'codex' / 'config.block.toml',
        render_codex_config_block(),
    )
    for wrapper in wrappers:
        name = wrapper['name']
        title = wrapper['title']
        target = wrapper['target']
        description = wrapper.get('description') or default_wrapper_description(title)
        add_rendered_file(
            outputs,
            BOOTSTRAP / 'claude' / 'commands' / f'{name}.md',
            render_claude_command(title, description, target),
        )
        add_rendered_file(
            outputs,
            BOOTSTRAP / 'codex' / 'skills' / name / 'SKILL.md',
            render_codex_skill(
                name, title, description, target, wrapper.get('codex_interaction')
            ),
        )
        add_rendered_file(
            outputs,
            BOOTSTRAP / 'opencode' / 'commands' / f'{name}.md',
            render_opencode_command(title, description, target),
        )
    for wrapper in pi_wrappers:
        add_rendered_file(
            outputs,
            BOOTSTRAP / 'pi' / 'prompts' / f"{wrapper['name']}.md",
            render_pi_prompt(wrapper),
        )
    rendered = tuple(RenderedFile(path, content) for path, content in outputs.items())
    validate_rendered_paths(rendered)
    return rendered


def validate_rendered_paths(rendered: tuple[RenderedFile, ...]) -> None:
    root = ROOT.resolve()
    canonical_paths: list[Path] = []
    for item in rendered:
        path = item.path
        if not path.is_absolute():
            raise SystemExit(f'bootstrap render target must be absolute: {path}')
        if path.is_symlink():
            raise SystemExit(f'bootstrap render target is a symlink: {path}')
        try:
            canonical = path.resolve(strict=False)
        except (OSError, RuntimeError) as exc:
            raise SystemExit(f'cannot resolve bootstrap render target: {path}') from exc
        if canonical == root or not canonical.is_relative_to(root):
            raise SystemExit(f'bootstrap render target escapes source root: {path}')
        if canonical != path:
            raise SystemExit(f'bootstrap render target is not canonical: {path}')
        canonical_paths.append(canonical)

    paths = tuple(canonical_paths)
    if len(paths) != len(set(paths)):
        raise SystemExit('duplicate bootstrap render target')
    for path in paths:
        if path.exists() and not path.is_file():
            raise SystemExit(f'bootstrap render target is not a regular file: {path}')
        current = path.parent
        while current != root:
            if current.is_symlink():
                raise SystemExit(f'bootstrap render target contains symlink: {current}')
            if current.exists() and not current.is_dir():
                raise SystemExit(f'bootstrap render parent is not a directory: {current}')
            current = current.parent
    for index, path in enumerate(paths):
        for other in paths[index + 1:]:
            if path in other.parents or other in path.parents:
                raise SystemExit(f'overlapping bootstrap render targets: {path}, {other}')


def git_blob(specifier: str) -> bytes | None:
    try:
        result = subprocess.run(
            ['git', 'show', specifier],
            cwd=ROOT,
            capture_output=True,
            check=False,
        )
    except OSError:
        return None
    return result.stdout if result.returncode == 0 else None


def preflight_rendered_bootstrap(rendered: tuple[RenderedFile, ...]) -> None:
    validate_rendered_paths(rendered)
    managed_paths = {
        ROOT / '.shared' / 'project' / 'index.md',
        ROOT / '.shared' / 'case' / 'README.md',
    }
    conflicts: list[tuple[str, str]] = []
    for item in rendered:
        path = item.path
        if path in managed_paths:
            continue
        relative = path.relative_to(ROOT).as_posix()
        head = git_blob(f'HEAD:{relative}')
        index = git_blob(f':{relative}')
        if not path.exists():
            if head is not None or index is not None:
                conflicts.append((relative, 'tracked generated source was removed'))
            continue
        try:
            current = path.read_bytes()
        except OSError as exc:
            conflicts.append((relative, f'cannot read generated source: {exc}'))
            continue
        if current == item.content:
            continue
        if head is not None and current == head and index == head:
            continue
        conflicts.append((relative, 'generated source contains uncommitted or untracked content'))
    if conflicts:
        details = '\n'.join(f'- {path}: {reason}' for path, reason in sorted(conflicts))
        raise SystemExit(f'bootstrap source ownership conflicts:\n{details}')


def snapshot_rendered_file(path: Path, backup: Path) -> RenderSnapshot:
    if path.is_symlink():
        raise OSError(f'refusing to snapshot symlink: {path}')
    if path.is_file():
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, backup)
        return RenderSnapshot(path, backup)
    if path.exists():
        raise OSError(f'unsupported bootstrap render target: {path}')
    return RenderSnapshot(path, None)


def remove_rendered_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
        return
    if path.is_dir():
        shutil.rmtree(path)
        return
    if path.exists():
        raise OSError(f'unsupported bootstrap render target: {path}')


def restore_render_snapshot(snapshot: RenderSnapshot) -> None:
    remove_rendered_path(snapshot.path)
    if snapshot.backup is None:
        return
    snapshot.path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(snapshot.backup, snapshot.path)


def new_render_parent_paths(rendered: tuple[RenderedFile, ...]) -> tuple[Path, ...]:
    missing: set[Path] = set()
    for item in rendered:
        current = item.path.parent
        while current != ROOT:
            if not current.exists():
                missing.add(current)
            current = current.parent
    return tuple(sorted(missing, key=lambda path: len(path.parts), reverse=True))


def write_rendered_file(item: RenderedFile) -> None:
    path = item.path
    path.parent.mkdir(parents=True, exist_ok=True)
    mode: int | None = None
    if path.exists() and not path.is_symlink() and path.is_file():
        mode = path.stat().st_mode & 0o7777
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            prefix=f'.{path.name}.',
            dir=path.parent,
            delete=False,
        ) as handle:
            temp_name = handle.name
            os.chmod(temp_name, mode if mode is not None else 0o644)
            handle.write(item.content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
        temp_name = None
    finally:
        if temp_name is not None:
            try:
                Path(temp_name).unlink()
            except FileNotFoundError:
                pass


def apply_rendered_bootstrap(rendered: tuple[RenderedFile, ...]) -> None:
    for item in rendered:
        write_rendered_file(item)


def run_render_transaction(rendered: tuple[RenderedFile, ...]) -> None:
    preflight_rendered_bootstrap(rendered)
    new_parents = new_render_parent_paths(rendered)
    with tempfile.TemporaryDirectory(prefix='agentwork-render-rollback-') as temp:
        backup_root = Path(temp)
        try:
            snapshots = tuple(
                snapshot_rendered_file(item.path, backup_root / str(index))
                for index, item in enumerate(rendered)
            )
        except (OSError, shutil.Error) as exc:
            raise SystemExit(f'cannot prepare bootstrap renderer backup: {exc}') from exc
        try:
            apply_rendered_bootstrap(rendered)
        except (Exception, KeyboardInterrupt, SystemExit) as exc:
            rollback_errors: list[str] = []
            for snapshot in reversed(snapshots):
                try:
                    restore_render_snapshot(snapshot)
                except (Exception, KeyboardInterrupt, SystemExit) as rollback_exc:
                    rollback_errors.append(f'{snapshot.path.relative_to(ROOT)}: {rollback_exc}')
            for path in new_parents:
                try:
                    path.rmdir()
                except FileNotFoundError:
                    pass
                except OSError as rollback_exc:
                    if path.exists():
                        rollback_errors.append(
                            f'{path.relative_to(ROOT)}: could not remove new directory: {rollback_exc}'
                        )
            if rollback_errors:
                details = '; '.join(rollback_errors)
                raise SystemExit(
                    f'bootstrap renderer failed: {exc}; rollback incomplete: {details}'
                ) from exc
            raise SystemExit(f'bootstrap renderer failed and rolled back: {exc}') from exc


def main() -> int:
    parser = argparse.ArgumentParser(description='Render bootstrap files or check them without writing.')
    parser.add_argument('--check', action='store_true', help='report missing or different outputs without writing')
    args = parser.parse_args()
    rendered = prepare_rendered_bootstrap()
    if args.check:
        drift: list[str] = []
        for item in rendered:
            try:
                if item.path.is_symlink() or item.path.read_bytes() != item.content:
                    drift.append(str(item.path.relative_to(ROOT)))
            except OSError:
                drift.append(str(item.path.relative_to(ROOT)))
        if drift:
            print('bootstrap output drift:\n' + '\n'.join(f'- {path}' for path in drift))
            return 1
        return 0
    run_render_transaction(rendered)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
