from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

from test_pi_adapter import BOOTSTRAP, REPO_ROOT, load_renderer


# Independent of spec.json so removing a command cannot shrink the expected set.
EXPECTED_COMMANDS = {'brain', 'plan', 'exec', 'review', 'case', 'commit'}
EXPECTED_CAPABILITIES = {'anydoc', 'research'}


class AdapterContractTest(unittest.TestCase):
    def setUp(self) -> None:
        name = f'agentwork_adapter_renderer_{id(self)}'
        self.renderer = load_renderer(BOOTSTRAP / 'render_bootstrap.py', name)
        self.addCleanup(sys.modules.pop, name, None)
        self.outputs = {
            item.path.relative_to(BOOTSTRAP).as_posix(): item.content
            for item in self.renderer.prepare_rendered_bootstrap()
            if item.path.is_relative_to(BOOTSTRAP)
        }

    def assert_wrapper(self, text: str, name: str, platform: str) -> None:
        lines = text.splitlines()
        self.assertEqual(lines[0], '---')
        end = lines.index('---', 1)
        fields = dict(line.split(': ', 1) for line in lines[1:end])
        self.assertEqual(len(fields), end - 1, 'duplicate frontmatter fields')
        self.assertEqual(set(fields), {'name', 'description'} if platform == 'codex' else {'description'})
        self.assertTrue(json.loads(fields['description']).strip())
        wrapper = next(item for item in self.renderer.SPEC['wrappers'] if item['name'] == name)
        self.assertEqual(json.loads(fields['description']), wrapper['description'])
        if platform == 'codex':
            self.assertEqual(fields['name'], name)
        self.assertIn('<!-- AUTO-GENERATED by agentwork bootstrap -->', text)
        self.assertEqual(sum(line.startswith(f'# /{name}') for line in lines), 1)
        self.assertIn(f"# {wrapper['title']}", lines)
        target = f'.shared/commands/{name}.md'
        self.assertEqual(text.count(target), 1)
        if platform == 'opencode':
            self.assertIn(f'@{target}', lines)
            self.assertEqual(text.count('$ARGUMENTS'), 1)
        else:
            self.assertIn(f'`{target}`', text)
            self.assertNotIn('@.shared/', text)
        self.assertNotIn('## 当前核心子命令', text)
        if platform == 'codex':
            self.assertEqual('## Codex 交互适配' in text, name in {'brain', 'plan'})
            if name in {'brain', 'plan'}:
                self.assertIn('`request_user_input`', text)

    def test_command_wrappers_have_fixed_sets_and_thin_bodies(self) -> None:
        for platform in ('claude', 'codex', 'opencode'):
            prefix = f'{platform}/skills/' if platform == 'codex' else f'{platform}/commands/'
            actual = {path for path in self.outputs if path.startswith(prefix)}
            # research is copied by the installer; only anydoc is rendered here.
            expected = (
                {f'{prefix}{name}/SKILL.md' for name in EXPECTED_COMMANDS | {'anydoc'}}
                if platform == 'codex'
                else {f'{prefix}{name}.md' for name in EXPECTED_COMMANDS}
            )
            with self.subTest(platform=platform):
                self.assertEqual(actual, expected)
            for name in sorted(EXPECTED_COMMANDS):
                path = f'{prefix}{name}/SKILL.md' if platform == 'codex' else f'{prefix}{name}.md'
                with self.subTest(platform=platform, command=name):
                    content = self.outputs[path]
                    self.assertEqual((BOOTSTRAP / path).read_bytes(), content)
                    self.assert_wrapper(content.decode('utf-8'), name, platform)

    def test_cursor_rules_have_fixed_set_and_workflow_references(self) -> None:
        rules = {path for path in self.outputs if path.startswith('cursor/rules/')}
        self.assertEqual(rules, {'cursor/rules/agentwork-bootstrap.mdc', 'cursor/rules/anydoc.mdc'})
        text = self.outputs['cursor/rules/agentwork-bootstrap.mdc'].decode('utf-8')
        lines = text.splitlines()
        self.assertEqual(lines[0], '---')
        end = lines.index('---', 1)
        fields = dict(line.split(': ', 1) for line in lines[1:end])
        self.assertEqual(len(fields), end - 1)
        self.assertEqual(set(fields), {'description', 'globs', 'alwaysApply'})
        self.assertTrue(fields['description'].strip())
        self.assertEqual(fields['alwaysApply'], 'true')
        self.assertEqual(fields['globs'], '[]')
        for name in EXPECTED_COMMANDS:
            self.assertIn(f'`.shared/commands/{name}.md`', text)
        self.assertFalse(any(path.startswith('cursor/commands/') for path in self.outputs))
        for path in rules:
            self.assertEqual((BOOTSTRAP / path).read_bytes(), self.outputs[path])

    def test_fresh_install_exposes_static_entry_contracts(self) -> None:
        # Repository installation contract, not a claim about runtime discovery.
        scratch = REPO_ROOT / '.tmp'
        scratch.mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(prefix='adapter-contract-', dir=scratch) as directory:
            project = Path(directory) / 'project'
            result = subprocess.run(
                [sys.executable, str(REPO_ROOT / 'install-bootstrap.py'), '-p', str(project)],
                cwd=REPO_ROOT, text=True, capture_output=True, check=False, timeout=30,
            )
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for platform in ('claude', 'codex', 'opencode'):
                root = project / f'.{platform}' / ('skills' if platform == 'codex' else 'commands')
                pattern = '*/SKILL.md' if platform == 'codex' else '*.md'
                entries = {p.parent.name if platform == 'codex' else p.stem for p in root.glob(pattern)}
                expected = EXPECTED_COMMANDS | EXPECTED_CAPABILITIES if platform == 'codex' else EXPECTED_COMMANDS
                with self.subTest(platform=platform):
                    self.assertEqual(entries, expected)
                for name in EXPECTED_COMMANDS:
                    path = root / name / 'SKILL.md' if platform == 'codex' else root / f'{name}.md'
                    with self.subTest(platform=platform, command=name):
                        self.assert_wrapper(path.read_text(encoding='utf-8'), name, platform)
                        self.assertTrue((project / f'.shared/commands/{name}.md').is_file())
            self.assertEqual(
                {p.name for p in (project / '.cursor/rules').glob('*.mdc')},
                {'agentwork-bootstrap.mdc', 'anydoc.mdc', 'research.mdc'},
            )
            self.assertEqual(
                (project / '.cursor/rules/agentwork-bootstrap.mdc').read_bytes(),
                self.outputs['cursor/rules/agentwork-bootstrap.mdc'],
            )
            self.assertEqual({p.stem for p in (project / '.pi/prompts').glob('*.md')}, EXPECTED_COMMANDS)


if __name__ == '__main__':
    unittest.main()
