from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


REPO_ROOT = Path(__file__).resolve().parents[2]
BOOTSTRAP = REPO_ROOT / '.agentwork/bootstrap'
EXPECTED_PI_COMMANDS = (
    'brain',
    'plan',
    'exec',
    'review',
    'aw-session',
    'commit',
)
EXPECTED_PI_RESERVED_COMMANDS = (
    'arminsayshi',
    'changelog',
    'clone',
    'compact',
    'copy',
    'debug',
    'dementedelves',
    'export',
    'fork',
    'hotkeys',
    'import',
    'llama',
    'login',
    'logout',
    'model',
    'name',
    'new',
    'quit',
    'reload',
    'resume',
    'scoped-models',
    'session',
    'settings',
    'share',
    'thinking',
    'tree',
    'trust',
)


def load_renderer(script: Path, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, script)
    if spec is None or spec.loader is None:
        raise RuntimeError(f'cannot load renderer: {script}')
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def tree_snapshot(root: Path) -> dict[str, tuple[str, bytes | str | None]]:
    snapshot: dict[str, tuple[str, bytes | str | None]] = {}
    for item in [root, *sorted(root.rglob('*'))]:
        relative = '.' if item == root else item.relative_to(root).as_posix()
        if item.is_symlink():
            snapshot[relative] = ('symlink', os.readlink(item))
        elif item.is_dir():
            snapshot[relative] = ('directory', None)
        else:
            snapshot[relative] = ('file', item.read_bytes())
    return snapshot


class PiAdapterTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix='agentwork-pi-adapter-')
        self.addCleanup(self.temp.cleanup)
        self.module_names: list[str] = []

    def tearDown(self) -> None:
        for name in self.module_names:
            sys.modules.pop(name, None)

    def load(self, script: Path):
        name = f'agentwork_pi_renderer_{id(self)}_{len(self.module_names)}'
        self.module_names.append(name)
        return load_renderer(script, name)

    def source_fixture(self, name: str) -> Path:
        source = Path(self.temp.name) / name
        shutil.copytree(BOOTSTRAP, source / '.agentwork/bootstrap')
        shutil.copytree(REPO_ROOT / '.shared/commands', source / '.shared/commands')
        for relative in ('.shared/project/index.md', '.shared/session/README.md', 'AGENTS.md'):
            src = REPO_ROOT / relative
            dst = source / relative
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        return source

    def test_pi_prompt_contract_and_generated_files_match(self) -> None:
        renderer = self.load(BOOTSTRAP / 'render_bootstrap.py')
        before = {
            item.path: item.path.read_bytes() if item.path.is_file() else None
            for item in renderer.prepare_rendered_bootstrap()
        }
        rendered = renderer.prepare_rendered_bootstrap()
        after = {
            item.path: item.path.read_bytes() if item.path.is_file() else None
            for item in rendered
        }
        self.assertEqual(after, before)

        pi_wrappers = renderer.validated_pi_wrappers()
        self.assertEqual(tuple(item['name'] for item in pi_wrappers), EXPECTED_PI_COMMANDS)
        reserved = tuple(renderer.SPEC['pi']['tui_reserved_commands'])
        self.assertEqual(reserved, EXPECTED_PI_RESERVED_COMMANDS)
        self.assertEqual(set(reserved) & set(EXPECTED_PI_COMMANDS), set())
        self.assertEqual(renderer.SPEC['pi']['compatibility_baseline'], '0.84.4')
        self.assertEqual(renderer.SPEC['pi']['tag_commit'], 'b79e4cc834970cca69daebffab7df1da7d1e52c4')
        session = next(item for item in renderer.SPEC['wrappers'] if item['name'] == 'session')
        self.assertEqual(session['title'], '/session [subcommand] [args]')
        self.assertEqual(session['target'], '.shared/commands/session.md')

        pi_outputs = {
            item.path.relative_to(renderer.BOOTSTRAP / 'pi' / 'prompts').as_posix(): item
            for item in rendered
            if item.path.is_relative_to(renderer.BOOTSTRAP / 'pi' / 'prompts')
        }
        self.assertEqual(set(pi_outputs), {f'{name}.md' for name in EXPECTED_PI_COMMANDS})
        self.assertNotIn('session.md', pi_outputs)
        for wrapper in pi_wrappers:
            item = pi_outputs[f"{wrapper['name']}.md"]
            text = item.content.decode('utf-8')
            self.assertEqual(item.path.read_bytes(), item.content)
            self.assertIn('<!-- AUTO-GENERATED by agentwork bootstrap -->', text)
            self.assertIn('$ARGUMENTS', text)
            self.assertEqual(text.count('$ARGUMENTS'), 1)
            self.assertIn(f"`{wrapper['target']}`", text)
            lines = text.splitlines()
            self.assertEqual(lines[0], '---')
            frontmatter_end = lines.index('---', 1)
            self.assertGreaterEqual(frontmatter_end, 2)
            fields = dict(line.split(': ', 1) for line in lines[1:frontmatter_end])
            self.assertEqual(json.loads(fields['description']), wrapper['description'])
            if wrapper['argument_hint'] is None:
                self.assertNotIn('argument-hint', fields)
            else:
                self.assertEqual(json.loads(fields['argument-hint']), wrapper['argument_hint'])
            self.assertNotIn('@.shared/', text)
            self.assertNotIn('Case', text)
        aw_session = pi_outputs['aw-session.md'].content.decode('utf-8')
        self.assertEqual(
            aw_session,
            '''---
description: "运行 agentwork 仓库会话工作流；不同于 Pi 内置 /session"
argument-hint: "[subcommand] [args]"
---

<!-- AUTO-GENERATED by agentwork bootstrap -->
# /aw-session [subcommand] [args]

按共享定义执行本命令。Pi 会按 prompt template 规则展开以下用户参数（可为空）：

$ARGUMENTS

## 执行前必读
- 完整读取主定义：`.shared/commands/session.md`
- 完整读取占位符规范：`.shared/constraints/placeholder-naming.md`
''',
        )

    def test_renderer_rejects_invalid_pi_spec_before_writes(self) -> None:
        mutations = (
            (
                'base-name-escape',
                lambda data: data['wrappers'][0].update(
                    name='../../../../../escaped-wrapper'
                ),
            ),
            ('path-separator', lambda data: data['wrappers'][0].update(pi_name='brain/test')),
            ('dot-name', lambda data: data['wrappers'][0].update(pi_name='.')),
            ('dotdot-name', lambda data: data['wrappers'][0].update(pi_name='..')),
            ('uppercase-name', lambda data: data['wrappers'][0].update(pi_name='Brain')),
            ('duplicate-name', lambda data: data['wrappers'][1].update(pi_name='brain')),
            ('reserved-name', lambda data: data['wrappers'][0].update(pi_name='session')),
            ('metadata-newline', lambda data: data['wrappers'][0].update(pi_description='bad\nvalue')),
            ('title-newline', lambda data: data['wrappers'][0].update(pi_title='/brain\nbad')),
            ('title-mismatch', lambda data: data['wrappers'][0].update(pi_title='/other')),
            ('target-escape', lambda data: data['wrappers'][0].update(target='../brain.md')),
            (
                'target-nested',
                lambda data: data['wrappers'][0].update(
                    target='.shared/commands/nested/brain.md'
                ),
            ),
            (
                'target-newline',
                lambda data: data['wrappers'][0].update(
                    target='.shared/commands/brain\n.md'
                ),
            ),
            (
                'target-missing',
                lambda data: data['wrappers'][0].update(
                    target='.shared/commands/missing.md'
                ),
            ),
            ('invalid-tag-commit', lambda data: data['pi'].update(tag_commit='not-a-commit')),
            (
                'unsorted-reserved',
                lambda data: data['pi']['tui_reserved_commands'].reverse(),
            ),
        )
        for index, (name, mutate) in enumerate(mutations):
            with self.subTest(variant=name):
                source = self.source_fixture(f'invalid-{index}')
                spec_path = source / '.agentwork/bootstrap/spec.json'
                data = json.loads(spec_path.read_text(encoding='utf-8'))
                mutate(data)
                spec_path.write_text(
                    json.dumps(data, ensure_ascii=False, indent=2) + '\n',
                    encoding='utf-8',
                )
                before = tree_snapshot(source)
                renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
                with self.assertRaises(SystemExit):
                    renderer.prepare_rendered_bootstrap()
                self.assertEqual(tree_snapshot(source), before)

    def test_standalone_renderer_rolls_back_write_failures(self) -> None:
        for index, failure in enumerate((OSError('injected write failure'), KeyboardInterrupt())):
            with self.subTest(failure=type(failure).__name__):
                source = self.source_fixture(f'rollback-{index}')
                renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
                rendered = renderer.prepare_rendered_bootstrap()
                original = renderer.write_rendered_file
                calls = 0

                def fail_after_write(item) -> None:
                    nonlocal calls
                    original(item)
                    calls += 1
                    if calls == 1:
                        raise failure

                renderer.write_rendered_file = fail_after_write
                before = tree_snapshot(source)
                with self.assertRaisesRegex(SystemExit, 'failed and rolled back'):
                    renderer.run_render_transaction(rendered)
                self.assertEqual(tree_snapshot(source), before)

    def test_renderer_replaces_hardlinked_output_without_external_write(self) -> None:
        source = self.source_fixture('hardlink-success').resolve()
        target = (source / '.agentwork/bootstrap/pi/prompts/brain.md').resolve()
        canonical = target.read_bytes()
        altered = canonical.replace(b'# /brain', b'# project-owned brain')
        target.write_bytes(altered)
        subprocess.run(['git', 'init', '-q'], cwd=source, check=True)
        subprocess.run(
            ['git', 'config', 'user.email', 'agentwork-test@example.invalid'],
            cwd=source,
            check=True,
        )
        subprocess.run(
            ['git', 'config', 'user.name', 'agentwork test'],
            cwd=source,
            check=True,
        )
        subprocess.run(
            ['git', 'add', target.relative_to(source).as_posix()],
            cwd=source,
            check=True,
        )
        subprocess.run(['git', 'commit', '-qm', 'altered generated baseline'], cwd=source, check=True)
        external = Path(self.temp.name) / 'renderer-external-hardlink.md'
        external.write_bytes(altered)
        target.unlink()
        os.link(external, target)

        renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
        rendered = renderer.prepare_rendered_bootstrap()
        renderer.run_render_transaction(rendered)

        self.assertEqual(external.read_bytes(), altered)
        self.assertEqual(target.read_bytes(), canonical)
        self.assertNotEqual(target.stat().st_ino, external.stat().st_ino)

    def test_renderer_hardlink_output_stays_external_on_rollback(self) -> None:
        source = self.source_fixture('hardlink-rollback').resolve()
        target = (source / '.agentwork/bootstrap/pi/prompts/brain.md').resolve()
        canonical = target.read_bytes()
        altered = canonical.replace(b'# /brain', b'# project-owned brain')
        target.write_bytes(altered)
        subprocess.run(['git', 'init', '-q'], cwd=source, check=True)
        subprocess.run(
            ['git', 'config', 'user.email', 'agentwork-test@example.invalid'],
            cwd=source,
            check=True,
        )
        subprocess.run(
            ['git', 'config', 'user.name', 'agentwork test'],
            cwd=source,
            check=True,
        )
        subprocess.run(
            ['git', 'add', target.relative_to(source).as_posix()],
            cwd=source,
            check=True,
        )
        subprocess.run(['git', 'commit', '-qm', 'altered generated baseline'], cwd=source, check=True)
        external = Path(self.temp.name) / 'renderer-external-hardlink-rollback.md'
        external.write_bytes(altered)
        target.unlink()
        os.link(external, target)

        renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
        rendered = renderer.prepare_rendered_bootstrap()
        original_write = renderer.write_rendered_file

        def fail_after_target(item) -> None:
            original_write(item)
            if item.path == target:
                raise OSError('injected hardlink renderer failure')

        renderer.write_rendered_file = fail_after_target
        before = tree_snapshot(source)
        with self.assertRaisesRegex(SystemExit, 'failed and rolled back'):
            renderer.run_render_transaction(rendered)

        self.assertEqual(tree_snapshot(source), before)
        self.assertEqual(external.read_bytes(), altered)
        self.assertEqual(target.read_bytes(), altered)
        self.assertNotEqual(target.stat().st_ino, external.stat().st_ino)

    def test_renderer_rejects_noncanonical_manifest_path(self) -> None:
        renderer = self.load(BOOTSTRAP / 'render_bootstrap.py')
        path = renderer.ROOT / '.agentwork/bootstrap/pi/prompts/../escaped.md'
        with self.assertRaisesRegex(SystemExit, 'not canonical'):
            renderer.validate_rendered_paths((renderer.RenderedFile(path, b''),))

    def test_renderer_preserves_untracked_generated_source_conflict(self) -> None:
        source = self.source_fixture('source-conflict')
        conflict = source / '.agentwork/bootstrap/pi/prompts/brain.md'
        conflict.write_text('project-owned source\n', encoding='utf-8')
        renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
        rendered = renderer.prepare_rendered_bootstrap()
        before = tree_snapshot(source)

        with self.assertRaisesRegex(SystemExit, 'bootstrap source ownership conflicts'):
            renderer.run_render_transaction(rendered)

        self.assertEqual(tree_snapshot(source), before)
        self.assertEqual(conflict.read_text(encoding='utf-8'), 'project-owned source\n')

    def test_renderer_preserves_staged_generated_source_conflict(self) -> None:
        source = self.source_fixture('staged-source-conflict')
        subprocess.run(['git', 'init', '-q'], cwd=source, check=True)
        subprocess.run(
            ['git', 'config', 'user.email', 'agentwork-test@example.invalid'],
            cwd=source,
            check=True,
        )
        subprocess.run(
            ['git', 'config', 'user.name', 'agentwork test'],
            cwd=source,
            check=True,
        )
        subprocess.run(['git', 'add', '.'], cwd=source, check=True)
        subprocess.run(
            ['git', 'commit', '-qm', 'fixture baseline'],
            cwd=source,
            check=True,
        )
        conflict = source / '.agentwork/bootstrap/pi/prompts/brain.md'
        conflict.write_text('staged project content\n', encoding='utf-8')
        subprocess.run(
            ['git', 'add', conflict.relative_to(source).as_posix()],
            cwd=source,
            check=True,
        )
        renderer = self.load(source / '.agentwork/bootstrap/render_bootstrap.py')
        rendered = renderer.prepare_rendered_bootstrap()
        before = tree_snapshot(source)
        index_before = (source / '.git/index').read_bytes()

        with self.assertRaisesRegex(SystemExit, 'bootstrap source ownership conflicts'):
            renderer.run_render_transaction(rendered)

        self.assertEqual(tree_snapshot(source), before)
        self.assertEqual((source / '.git/index').read_bytes(), index_before)
        self.assertEqual(conflict.read_text(encoding='utf-8'), 'staged project content\n')


if __name__ == '__main__':
    unittest.main()
